import { createClient } from '@supabase/supabase-js';

type AnyRecord = Record<string, any>;
type FormField = { name:string; label:string; type:string; required:boolean; relevant?:string; constraint?:string; options?:Array<{name:string;label:string}> };
type DraftField = { name:string; label:string; value:string; confidence:number; evidence:string; status:'review'|'approved'|'rejected' };
type Draft = { id?:string; projectId:string; label:string; mode:'synthetic'; fields:DraftField[]; createdAt:string; status?:'review'|'confirmed'|'deployed' };

const table='fieldmind_records';
const defaultProject={id:'demo-thika',name:'Thika Level 5 NCD Community Study',location:'Thika Level 5 Hospital, Kiambu County',topic:'Health-seeking behavior for non-communicable diseases among adult men',koboUrl:'https://ee.kobotoolbox.org/x/IowlqBLK',formStatus:'Needs inspection',offlineReady:false,researchCount:0,draftCount:0,approvedCount:0,updatedAt:'Today'};

function db(){const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||'';const key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||'';if(!url||!key)throw new Error('Supabase is not configured');return createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}})}
async function list<T>(collection:string,limit=500){const {data,error}=await db().from(table).select('id,record').eq('collection',collection).order('created_at',{ascending:false}).limit(limit);if(error)throw error;return (data||[]).map((r:any)=>({...r.record,id:r.id})) as T[]}
async function insert(collection:string,records:AnyRecord[]){const {data,error}=await db().from(table).insert(records.map(record=>({collection,record}))).select('id');if(error)throw error;return (data||[]).map((r:any)=>r.id)}
async function update(id:string,record:AnyRecord){const {data,error}=await db().from(table).update({record,updated_at:new Date().toISOString()}).eq('id',id).select('id');if(error)throw error;return Boolean(data?.length)}
async function remove(id:string){const {data,error}=await db().from(table).delete().eq('id',id).select('id');if(error)throw error;return Boolean(data?.length)}
async function seed(){const p=await list<AnyRecord>('projects',10);if(p.length)return p;const ids=await insert('projects',[{...defaultProject}]);return [{...defaultProject,id:ids[0]}]}

function send(res:any,status:number,payload:any){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').json(payload)}
function bodyOf(req:any):AnyRecord{if(!req.body)return{};if(typeof req.body==='string'){try{return JSON.parse(req.body)}catch{return{}}}return req.body}
function safeKobo(url:string){try{const u=new URL(url);return u.protocol==='https:'&&(u.hostname.endsWith('kobotoolbox.org')||u.hostname.endsWith('humanitarianresponse.info'))}catch{return false}}
function clean(s:string){return s.replace(/<script[\\s\\S]*?<\\/script>/gi,' ').replace(/<style[\\s\\S]*?<\\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\\s+/g,' ').trim()}
function attr(s:string,k:string){const m=s.match(new RegExp('\\\\b'+k+'=["\\\\\']([^"\\\\\']*)["\\\\\']','i'));return m?.[1]||''}
function uidFrom(s:string){return s.match(/(?:#\\/forms\\/|\\/forms\\/)([A-Za-z0-9]+)(?:\\/|$)/)?.[1]||''}

function parseXForm(xml:string):{title:string;fields:FormField[]}{
  const title=clean(xml.match(/<(?:h:)?title[^>]*>([\\s\\S]*?)<\\/(?:h:)?title>/i)?.[1]||'KoboToolbox form');
  const binds=new Map<string,AnyRecord>();
  for(const m of xml.matchAll(/<(?:bind|xf:bind)\\b([^>]*)\\/?>(?:<\\/(?:bind|xf:bind)>)?/gi)){const ref=attr(m[1],'nodeset')||attr(m[1],'ref');if(ref)binds.set(ref,{type:attr(m[1],'type'),required:attr(m[1],'required'),relevant:attr(m[1],'relevant'),constraint:attr(m[1],'constraint'),calculation:attr(m[1],'calculate')||attr(m[1],'jr:calculate')})}
  const fields:FormField[]=[];const seen=new Set<string>();
  const add=(ref:string,fallback:string,body:string)=>{const name=ref.replace(/^\\//,'').replace(/^data\\//,'');if(!name||seen.has(name)||/^meta\\//i.test(name))return;const b=binds.get(ref)||binds.get('/'+name)||binds.get(name)||{};const label=clean(body.match(/<(?:h:)?label\\b[^>]*>([\\s\\S]*?)<\\/(?:h:)?label>/i)?.[1]||name.replace(/[_-]+/g,' '));const options:Array<{name:string;label:string}>=[];for(const item of body.matchAll(/<item\\b[^>]*>([\\s\\S]*?)<\\/item>/gi)){const value=item[1].match(/<(?:h:)?value\\b[^>]*>([\\s\\S]*?)<\\/(?:h:)?value>/i)?.[1];if(value)options.push({name:clean(value),label:clean(item[1].match(/<(?:h:)?label\\b[^>]*>([\\s\\S]*?)<\\/(?:h:)?label>/i)?.[1]||value)})}const type=b.type||fallback||'text';if(/calculate|note|hidden/i.test(type)||b.calculation)return;seen.add(name);fields.push({name,label,type,required:/true\\(\\)|true|1/i.test(b.required||''),...(b.relevant?{relevant:b.relevant}:{}),...(b.constraint?{constraint:b.constraint}:{}),...(options.length?{options}: {})})};
  const control=/<(?:input|select1|select|textarea|upload|range|geopoint|date|datetime|time)\\b([^>]*)(?:\\/>|>([\\s\\S]*?)<\\/(?:input|select1|select|textarea|upload|range|geopoint|date|datetime|time)>)/gi;
  for(const m of xml.matchAll(control)){const ref=attr(m[1]||'','ref');if(ref)add(ref,(m[0].match(/^<([a-z0-9:_-]+)/i)?.[1]||'input').replace(/^.*:/,''),m[2]||'')}
  if(!fields.length)for(const [ref,b] of binds)if(b.type&&!/calculate|note|hidden/i.test(b.type))add(ref,b.type,'');
  return {title,fields}
}
async function fetchText(url:string,headers:AnyRecord={}){const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'FieldMind-Research/5.0',Accept:'text/html,application/xml,text/xml,application/json',...headers}});return {r,text:await r.text()}}
async function aiJson(system:string,prompt:string,name:string,schema:AnyRecord){const key=process.env.OPENAI_API_KEY;if(!key)return null;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',store:false,input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:[{type:'input_text',text:prompt}]}],text:{format:{type:'json_schema',name,strict:true,schema}},max_output_tokens:8192})});if(!r.ok)throw new Error('AI request failed: '+r.status);const d=await r.json() as any;return d.output_text?JSON.parse(d.output_text):null}

async function inspectKobo(url:string,source:string,token:string){
  const uid=source||uidFrom(url);const auth=token||process.env.KOBO_API_TOKEN||'';const headers=auth?{Authorization:'Token '+auth}:{};
  if(uid)for(const base of ['https://kf.kobotoolbox.org','https://eu.kobotoolbox.org'])for(const endpoint of ['/api/v2/assets/'+encodeURIComponent(uid)+'.xml','/api/v2/assets/'+encodeURIComponent(uid)+'/xform/']){try{const x=await fetchText(base+endpoint,headers);if(x.r.ok){const p=parseXForm(x.text);if(p.fields.length)return {...p,source:'Kobo API XForm',resolvedUrl:x.r.url}}}catch{}}
  try{const x=await fetchText(url);if(x.r.ok){const p=parseXForm(x.text);if(p.fields.length)return {...p,source:'Kobo web form XForm',resolvedUrl:x.r.url};const extracted=await aiJson('Extract the exact questionnaire structure from the supplied KoboToolbox page text. Never invent questions, field names or choices.','PAGE TEXT:\\n'+clean(x.text).slice(0,45000),'kobo_form_definition',{type:'object',properties:{title:{type:'string'},fields:{type:'array',items:{type:'object',properties:{name:{type:'string'},label:{type:'string'},type:{type:'string'},required:{type:'boolean'},relevant:{type:'string'},options:{type:'array',items:{type:'object',properties:{name:{type:'string'},label:{type:'string'}},required:['name','label'],additionalProperties:false}}},required:['name','label','type','required','relevant','options'],additionalProperties:false}}},required:['title','fields'],additionalProperties:false});if(extracted?.fields?.length)return{title:extracted.title||'KoboToolbox form',fields:extracted.fields,source:'Kobo AI extraction',resolvedUrl:x.r.url}}}catch{}
  return null
}
function synthetic(field:FormField,i:number,r:number){const prefix='SYNTHETIC_TEST_'+String(r+1).padStart(3,'0');if(field.options?.length)return field.options[(i+r)%field.options.length].name;if(/integer|decimal|range/i.test(field.type))return String((i%9)+1);if(/date/i.test(field.type))return '2099-01-'+String((r%28)+1).padStart(2,'0');if(/time/i.test(field.type))return '12:00:00';if(/geopoint/i.test(field.type))return '0 0 0 0';return prefix+'_'+field.name.toUpperCase().replace(/[^A-Z0-9]+/g,'_')}
function chunks(n:number,size:number){const out:number[][]=[];for(let i=0;i<n;i+=size)out.push(Array.from({length:Math.min(size,n-i)},(_,j)=>i+j));return out}

async function generate(project:AnyRecord,fields:FormField[],indexes:number[],ageMix:string,majority:string){
 const fieldText=fields.map((f,i)=>JSON.stringify({order:i+1,...f})).join('\n');
 return aiJson('Create SYNTHETIC QA fixtures for a KoboToolbox questionnaire. These are test fixtures, not participant records. Include every supplied field exactly once. Use only supplied choice values. Respect required, relevant and constraint information. For conditional fields that are not applicable, use __NOT_APPLICABLE_BY_FORM_LOGIC__. Free text must be explicitly synthetic. Never invent real identities or observed research facts.','PROJECT: '+String(project.name||'')+'\\nTOPIC: '+String(project.topic||'')+'\\nCONFIG: age mix='+ageMix+'; majority guidance='+majority+'\\nFORM DEFINITION:\\n'+fieldText+'\\nRECORD INDEXES: '+indexes.join(', '),'synthetic_qa_fixtures',{type:'object',properties:{drafts:{type:'array',items:{type:'object',properties:{label:{type:'string'},fields:{type:'array',items:{type:'object',properties:{name:{type:'string'},value:{type:'string'},confidence:{type:'number'},evidence:{type:'string'}},required:['name','value','confidence','evidence'],additionalProperties:false}}},required:['label','fields'],additionalProperties:false}}},required:['drafts'],additionalProperties:false})
}

export default async function handler(req:any,res:any){
 try{
  if(req.method==='OPTIONS'){res.status(204).end();return}
  const path=new URL(req.url||'/', 'https://fieldmind.local').pathname.replace(/\\/$/,'')||'/';const body=bodyOf(req);
  if(req.method==='GET'&&path==='/api/_healthcheck'){const configured=Boolean(process.env.SUPABASE_URL&&(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY));send(res,200,{ok:true,database:configured?'configured':'missing',ai:process.env.OPENAI_API_KEY?'configured':'missing'});return}
  if(req.method==='GET'&&path==='/api/projects'){send(res,200,{projects:await seed()});return}
  if(req.method==='POST'&&path==='/api/projects'){if(!body.name||!body.location||!body.topic){send(res,400,{message:'Project name, location and topic are required'});return}const ids=await insert('projects',[body]);send(res,200,{project:{...body,id:ids[0]}});return}
  if(req.method==='GET'&&path==='/api/drafts'){send(res,200,{drafts:await list<Draft>('drafts',500)});return}
  const match=path.match(/^\\/api\\/drafts\\/([^/]+)$/);
  if(match&&req.method==='PUT'){const id=match[1];const ok=await update(id,{...body,id});send(res,ok?200:404,{draft:{...body,id}});return}
  if(match&&req.method==='DELETE'){const ok=await remove(match[1]);send(res,ok?200:404,{deleted:ok});return}
  if(req.method==='POST'&&path==='/api/kobo/inspect'){const url=String(body.url||'');if(!safeKobo(url)){send(res,400,{message:'Use a valid KoboToolbox HTTPS form URL'});return}const resolved=await inspectKobo(url,String(body.assetUid||''),String(body.apiToken||''));if(!resolved){send(res,422,{reachable:true,mapped:false,questionCount:0,fields:[],needsAssetUid:!body.assetUid,message:'Form page reached, but the questionnaire definition was not resolved. Paste the Kobo project URL or Asset UID for exact XForm mapping.'});return}send(res,200,{reachable:true,mapped:true,title:resolved.title,offlineReady:true,questionCount:resolved.fields.length,fields:resolved.fields,source:resolved.source,resolvedUrl:resolved.resolvedUrl});return}
  if(req.method==='POST'&&path==='/api/ai/drafts'){const fields=(Array.isArray(body.fields)?body.fields:[]) as FormField[];if(!fields.length){send(res,400,{message:'Inspect the Kobo form first; no questionnaire definition is available'});return}const count=Math.max(1,Math.min(100,Number(body.count)||1));const project=(body.project||{}) as AnyRecord;const out:Draft[]=[];for(const batch of chunks(count,20)){let aiOut:any=null;try{aiOut=await generate(project,fields,batch,String(body.ageMix||''),String(body.majority||''))}catch(e){console.error(e)}batch.forEach((recordIndex,offset)=>{const gen=aiOut?.drafts?.[offset];const map=new Map((gen?.fields||[]).map((f:any)=>[String(f.name||''),f]));out.push({projectId:String(project.id||''),label:String(gen?.label||'Synthetic QA fixture '+String(recordIndex+1).padStart(3,'0')),mode:'synthetic',fields:fields.map((f,i)=>{const c=map.get(f.name);return{name:f.name,label:f.label,value:String(c?.value||synthetic(f,i,recordIndex)),confidence:Math.max(0,Math.min(100,Number(c?.confidence)||100)),evidence:String(c?.evidence||'Synthetic QA value; not observed participant data.'),status:'review'}}),createdAt:new Date().toISOString(),status:'review'})})}const ids=await insert('drafts',out as any);send(res,200,{drafts:out.map((d,i)=>({...d,id:ids[i]})),mode:'synthetic',questionCount:fields.length});return}
  if(req.method==='POST'&&path==='/api/drafts/confirm-all'){const pid=String(body.projectId||'');const items=(await list<Draft>('drafts',500)).filter(d=>d.projectId===pid);if(!pid||!items.length){send(res,400,{message:'No records found for this project'});return}if(items.some(d=>!d.fields.length||d.fields.some(f=>!f.name||!f.value))){send(res,400,{message:'Every mapped question needs a value or explicit form-logic skip marker'});return}await Promise.all(items.map(d=>update(String(d.id),{...d,status:'confirmed',fields:d.fields.map(f=>({...f,status:'approved'}))})));send(res,200,{confirmed:true,message:'Everything is confirmed. Controlled package preparation is unlocked.'});return}
  if(req.method==='POST'&&path==='/api/drafts/deploy'){const pid=String(body.projectId||'');const items=(await list<Draft>('drafts',500)).filter(d=>d.projectId===pid);if(!items.length){send(res,400,{message:'No records found for this project'});return}if(items.some(d=>d.status!=='confirmed'&&d.status!=='deployed')){send(res,409,{message:'Deployment locked until every record is confirmed'});return}await Promise.all(items.map(d=>update(String(d.id),{...d,status:'deployed'})));send(res,200,{deployed:true,packagePrepared:true,message:'Controlled synthetic QA package prepared. No live Kobo submission was performed.'});return}
  send(res,404,{message:'Route not found'})
 }catch(e){console.error('FieldMind API error',e);send(res,500,{message:e instanceof Error?e.message:'Internal server error'})}
}